version: '3.7'

services:
  database:
    container_name: database
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${DB_EXTERNAL_PORT}:5432

  backend:
    restart: always
    build:
      context: ./backend
    entrypoint: wait-for database:5432 -- /usr/bin/entrypoint.sh
    command: npm run start
    environment:
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_HOST
      - DB_PASSWORD
      - SITE_HOST
      - SECRET_KEY
    depends_on:
      - database
    ports:
      - 8001:3000

  admin:
    restart: always
    build:
      context: ./admin
      args:
        BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend

    ports:
      - 8000:3000
