version: '3.7'

services:
  backend:
    restart: always
    build:
      context: ./backend
    entrypoint: wait-for database:5432 -- /usr/bin/entrypoint.sh
    command: npm run dev
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

